Use cached if download failed but log the failure
In order to avoid deploys getting blocked if a new version can't be
downloaded, we use the cached version but log the failure so that we can
monitor and alert.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -46,17 +46,17 @@ mkdir -p "$LIBMAXMINDDB_CACHE_DIST_DIR"
 echo "       Downloading GeoLite2 City and Country data"
 
 if [ "$(cat ${GEOIP_CACHE_VERSION_FILE} 2>/dev/null)" != "${DATE}" ]; then
-  curl -L -z ${GEOIP_CACHE_DIR}/${GEOLITE2_COUNTRY_TARBALL_FILENAME} -o ${GEOLITE2_COUNTRY_TARBALL_FILENAME} \
-    "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz"
-
-  if [ -f "${GEOLITE2_COUNTRY_TARBALL_FILENAME}" ]; then
+  if ! curl -L -z ${GEOIP_CACHE_DIR}/${GEOLITE2_COUNTRY_TARBALL_FILENAME} -o ${GEOLITE2_COUNTRY_TARBALL_FILENAME} \
+    "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz"; then
+    echo "       Failed to download GeoLite2 Country data. Using cached version."
+  elif [ -f "${GEOLITE2_COUNTRY_TARBALL_FILENAME}" ]; then
     mv ${GEOLITE2_COUNTRY_TARBALL_FILENAME} ${GEOIP_CACHE_DIR}/${GEOLITE2_COUNTRY_TARBALL_FILENAME}
   fi
 
-  curl -L -z ${GEOIP_CACHE_DIR}/${GEOLITE2_CITY_TARBALL_FILENAME} -o ${GEOLITE2_CITY_TARBALL_FILENAME} \
-    "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz"
-
-  if [ -f "${GEOLITE2_CITY_TARBALL_FILENAME}" ]; then
+  if ! curl -L -z ${GEOIP_CACHE_DIR}/${GEOLITE2_CITY_TARBALL_FILENAME} -o ${GEOLITE2_CITY_TARBALL_FILENAME} \
+    "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=$MAXMIND_LICENSE_KEY&suffix=tar.gz"; then
+    echo "       Failed to download GeoLite2 City data. Using cached version."
+  elif [ -f "${GEOLITE2_CITY_TARBALL_FILENAME}" ]; then
     mv ${GEOLITE2_CITY_TARBALL_FILENAME} ${GEOIP_CACHE_DIR}/${GEOLITE2_CITY_TARBALL_FILENAME}
   fi
 
